// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("WebApplication1.Models.TemperaturaSensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<double>("Sensor1")
                        .HasColumnType("REAL");

                    b.Property<double>("Sensor2")
                        .HasColumnType("REAL");

                    b.Property<double>("Sensor3")
                        .HasColumnType("REAL");

                    b.Property<double>("Sensor4")
                        .HasColumnType("REAL");

                    b.Property<double>("Sensor5")
                        .HasColumnType("REAL");

                    b.Property<double>("Sensor6")
                        .HasColumnType("REAL");

                    b.Property<double>("Sensor7")
                        .HasColumnType("REAL");

                    b.Property<double>("Sensor8")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Temperaturas");
                });
#pragma warning restore 612, 618
        }
    }
}
